apiVersion: v1
kind: Service
metadata:
  name: nginx-tls-service
  labels:
    app: nginx-tls
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-tls
